ALTER TABLE kb_notes ADD COLUMN file_type VARCHAR(20) DEFAULT '';
ALTER TABLE kb_notes ADD COLUMN file_size BIGINT DEFAULT 0;
ALTER TABLE kb_notes ADD COLUMN tags VARCHAR(2000) DEFAULT '[]';
ALTER TABLE kb_notes ADD COLUMN status VARCHAR(20) DEFAULT 'ready';
