ALTER TABLE kb_notes ADD COLUMN file_type VARCHAR(20) DEFAULT '';
ALTER TABLE kb_notes ADD COLUMN file_size BIGINT DEFAULT 0;
ALTER TABLE kb_notes ADD COLUMN tags VARCHAR(2000) DEFAULT '[]';
ALTER TABLE kb_notes ADD COLUMN status VARCHAR(20) DEFAULT 'ready';
ALTER TABLE kb_notes ADD COLUMN created_by VARCHAR(50) DEFAULT '';
ALTER TABLE kb_notes ADD COLUMN original_file VARCHAR(255) DEFAULT '';
ALTER TABLE kb_notes ADD COLUMN category_id BIGINT DEFAULT NULL;

CREATE TABLE IF NOT EXISTS kb_categories (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  kb_id BIGINT NOT NULL DEFAULT 0,
  name VARCHAR(100) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_at VARCHAR(30) DEFAULT ''
  updated_at VARCHAR(30) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
